Go

USE MODULE1

-- COMMIT: To save transactions from database log file to the data file
-- ROLLBACK: To undo the transaction

-- AUTO COMMIT : AUTO START, AUTO END
-- EXPLICIT COMMIT : MANUAL START, MANUAL END
-- IMPLICIT COMMIT : AUTO START MANUAL END 

SELECT * FROM RESERVATION
 -- AUTO COMMIT
INSERT INTO RESERVATION VALUES('EMT104', 2, '3')
INSERT INTO RESERVATION VALUES('EMT105', 3, '4')

TRUNCATE TABLE RESERVATION

SELECT * FROM RESERVATION

--EXPLICIT COMMIT
BEGIN TRANSACTION t1
INSERT INTO RESERVATION VALUES('EMT106', 4, '5')
DECLARE @RWCOUNT INTEGER
SELECT @RWCOUNT = COUNT(*) FROM RESERVATION 
IF @RWCOUNT > 1
COMMIT
ELSE
ROLLBACK

-- IMPLICIT TRANSACTIONS
SET IMPLICIT_TRANSACTIONS ON
INSERT INTO RESERVATION VALUES('EMT107', 5, '6')
DECLARE @Code VARCHAR(50)
SELECT @Code = Class_Code FROM RESERVATION
IF @Code = 'EMT110'
COMMIT
ELSE
ROLLBACK
SET IMPLICIT_TRANSACTIONS OFF

SELECT * FROM RESERVATION

-- OPEN TRANSACTIONS (The Transactions Which Are Not Commited And RollBack)
-- Impact OF Open Transactions - Query Blocking
SELECT * FROM RESERVATION

SELECT * FROM RESERVATION(NOLOCK) -- It Shows Uncomitted Data

SELECT * FROM RESERVATION(READPAST) -- No Query Blocking and No Dirty Data



